### ISSUE TITLE
feedback on RFC-0001

### ISSUE THREAD

**Issue by marshallshen** [HackerPen/rfcs#1]
## RFC-0001 interview review

https://github.com/HackerPen/rfcs/tree/main/active/0001-interview-review.md

React to this issue:
👍  if you like this feature (comment to tell us why 😃  )
👎  if you don't like this feature (comment to tell us why 😄 )

**Comment by iandouglas** [comment]
I think it would be nice to give feedback right away instead of 4 hours later when you might forget details.
Perhaps another pane/panel to collect notes during the interview as well so we can stay within the UI.

**Comment by marshallshen** [comment]
@iandouglas 
Good point! I think immediately after the start time of an interview, an authorized user should be able to give feedback.
Re - adding a panel to save notes: also a good point, so that users can stay all within the UI.
